# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=10, max_digits=19)),
                ('high', models.DecimalField(decimal_places=10, max_digits=19)),
                ('low', models.DecimalField(decimal_places=10, max_digits=19)),
                ('close', models.DecimalField(decimal_places=10, max_digits=19)),
                ('volume', models.BigIntegerField()),
                ('adj_close', models.DecimalField(decimal_places=10, max_digits=19)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
